before_install:
  - rvm get head
bundler_args: --without development
language: ruby
cache: bundler
rvm:
  - rbx-18mode
  - rbx-19mode
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: 1.8.7
    - rvm: 2.1.0
